[package]
name = "rs-xsheets2stats"
version = "0.1.0"
edition = "2024"

description = "Prints the stats of the sheets of the book."
license = "Apache-2.0"
repository = "https://github.com/takanoriyanagitani/rs-xsheets2stats"
homepage = "https://github.com/takanoriyanagitani/rs-xsheets2stats"
documentation = "https://docs.rs/rs-xsheets2stats/latest"
keywords = ["xlsx", "stat", "count", "rows", "cells"]

exclude = [
    "rs-xsheets2stats.wasm",
    "opt.wasm",
    "sample.d/input.xlsx",
]

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"

[profile.release-wasi]
inherits = "release"
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[dependencies.clap]
version = "4"
default-features = false
features = [
    "std",
    "derive",
    "help",
    "usage",
]

[dependencies.calamine]
version = "0.34"
default-features = false
features = [
]
